name: Build and Release with Ant

on:
  workflow_dispatch:  # Manual trigger from GitHub UI

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'

      - name: Install Apache Ant
        run: sudo apt-get update && sudo apt-get install -y ant

      - name: Build ZIP with Ant
        run: ant zip

      - name: Upload release ZIP to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
